"""empty message

Revision ID: abf5214cdcec
Revises: 
Create Date: 2021-05-12 01:10:23.985886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abf5214cdcec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=120), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('pin', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('pin'),
    sa.UniqueConstraint('pin')
    )
    op.create_table('lugares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('ubicacion', sa.String(length=120), nullable=False),
    sa.Column('petFriendly', sa.String(length=120), nullable=False),
    sa.Column('accesoTransporte', sa.String(length=120), nullable=False),
    sa.Column('baños', sa.String(length=120), nullable=False),
    sa.Column('actividades', sa.String(length=120), nullable=False),
    sa.Column('electricidad', sa.String(length=120), nullable=False),
    sa.Column('ambiente', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=120), nullable=False),
    sa.Column('contacto', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actividades'),
    sa.UniqueConstraint('actividades'),
    sa.UniqueConstraint('contacto'),
    sa.UniqueConstraint('contacto'),
    sa.UniqueConstraint('descripcion'),
    sa.UniqueConstraint('descripcion'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('telefono'),
    sa.UniqueConstraint('telefono'),
    sa.UniqueConstraint('ubicacion'),
    sa.UniqueConstraint('ubicacion')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=120), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('pin', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('pin'),
    sa.UniqueConstraint('pin')
    )
    op.create_table('visitas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=250), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('calificacion', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calificacion'),
    sa.UniqueConstraint('calificacion')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visitas')
    op.drop_table('user')
    op.drop_table('lugares')
    op.drop_table('empresario')
    # ### end Alembic commands ###
